apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: nginx-prod-vpa
  namespace: nginx-prod
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: prod-nginx
  updatePolicy:
    updateMode: "Off"  # Recommendation mode only - do not apply
  resourcePolicy:
    containerPolicies:
      - containerName: nginx
        minAllowed:
          cpu: 50m
          memory: 64Mi
        maxAllowed:
          cpu: 500m
          memory: 512Mi
        controlledResources: ["cpu", "memory"]

