# Velero RBAC for prod
# ClusterRole and ClusterRoleBinding for Velero server to access cluster resources

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: velero-server
  labels:
    app: velero
rules:
  - apiGroups:
      - '*'
    resources:
      - '*'
    verbs:
      - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: velero-server
  labels:
    app: velero
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: velero-server
subjects:
  - kind: ServiceAccount
    name: velero
    namespace: velero-prod
