apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gatekeeper-prod
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  
  source:
    repoURL: https://open-policy-agent.github.io/gatekeeper/charts
    chart: gatekeeper
    targetRevision: 3.14.0
    helm:
      releaseName: gatekeeper
      values: |
        enableExternalData: false
        enableGeneratorResourceExpansion: false
        replicas: 3
        webhook:
          namespaceSelector:
            matchExpressions:
              - key: control-plane
                operator: DoesNotExist
              - key: admission.gatekeeper.sh/ignore
                operator: DoesNotExist
          excludedOperations:
            - "*"
          excludedNamespaces:
            - kube-system
            - kube-public
            - kube-node-lease
            - gatekeeper-system
            - argocd
            - vertical-pod-autoscaler
            - velero-prod
    
  destination:
    server: https://kubernetes.default.svc
    namespace: gatekeeper-system
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
    
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m

