apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gatekeeper-policy-manager-prod
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  
  source:
    repoURL: https://github.com/sighupio/gatekeeper-policy-manager/
    path: manifests
    targetRevision: main   
    helm:
      releaseName: gatekeeper-policy-manager
      values: |
        service:
          type: LoadBalancer
          port: 8888
        ingress:
          enabled: true
    
  destination:
    server: https://kubernetes.default.svc
    namespace: gatekeeper-system
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
    
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m

