
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubecost-dev
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  
  source:
    repoURL: https://kubecost.github.io/cost-analyzer
    chart: cost-analyzer
    targetRevision: 2.8.0
    helm:
      releaseName: kubecost
      values: |
        global:
          clusterId: dev-gke
          prometheus:
            enabled: true
        service:
          type: LoadBalancer
          port: 9090
        ingress:
          enabled: false
        kubecostProductConfigs:
          currencyCode: USD
    
  destination:
    server: https://kubernetes.default.svc
    namespace: kubecost-dev
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
    
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m

