apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubeview-prod
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  
  source:
    repoURL: https://benc55.github.io/kubeview
    chart: kubeview
    targetRevision: 0.2.0
    helm:
      releaseName: kubeview
      values: |
        service:
          type: LoadBalancer
          port: 80
        ingress:
          enabled: false
    
  destination:
    server: https://kubernetes.default.svc
    namespace: kubeview-prod
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
    
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m

